### ISSUE TITLE
 Where should i add my avatar and username

### ISSUE THREAD

**Issue by cocodisme** [aliahmadcse/linktree-clone#5]
I made some modifications in fronend and backend too like added background image instead of color and added my avatar . ![image](https://cdn.discordapp.com/attachments/907250155638648862/908073076615434250/s.png)
I kindly request you to help me to add avatar and username in linktree.clone/username along with the links in usercontroller.

Thankyou

**Comment by aliahmadcse** [comment]
Thank you for opening the Issue @cocodisme. Can you please open a PR with your changes to add it to the project overall?
That would be great. Thanks!
